### PR TITLE
[JENKINS-33309] Allow SCMHead to have actions, and define ChangeRequestAction

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-33309](https://issues.jenkins-ci.org/browse/JENKINS-33309)

@reviewbybees esp. @imeredith

### CODE REVIEW

**Comment by stephenc** [comment]
:bee:

**Comment by amuniz** [comment]
:bee:

**Comment by stephenc** [comment]
:+1: as maintainer

**Comment by jglick** [comment]
I had actually intended to wait until the whole set of four related PRs was reviewed before merging any or asking for merges, but OK.

**Pull request merged**
