### PR TITLE
Don't rely on core resource in test (will be removed soon in core)

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/jenkins/pull/5778 and https://github.com/jenkinsci/bom/pull/729

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Review by olamy — APPROVED** [review]

**Comment by timja** [comment]
Could this be released please?

tests passed on bom for updated core: https://github.com/jenkinsci/bom/pull/729

**Comment by timja** [comment]
release please @jenkinsci/scm-api-plugin-developers

**Comment by timja** [comment]
@jenkinsci/scm-api-plugin-developers / @jglick pretty please?

**Comment by timja** [comment]
Thanks Jesse!

**Pull request merged**
