### PR TITLE
Use upstream ASM provided by Jenkins core rather than repackaged ASM provided by Jenkins core

### PR DESCRIPTION
**Pull request by basil**
In Jenkins 2.222.4 (the minimum version of Jenkins required by this plugin), both upstream ASM (5.0.3) and Kohsuke's repackaged ASM (5.0.1) are provided by Jenkins core. In the latest LTS and weekly, both upstream ASM (9.1) and Kohsuke's repackaged ASM (5.0.1) are provided by Jenkins core.

This plugin consumes Kohsuke's repackaged version of ASM. I would like to remove this from Stapler and Jenkins core, so in this PR I am switching this plugin to rely on the upstream ASM provided by Jenkins core. As a bonus, this will effectively mean that when running on recent versions of Jenkins core this plugin will get the latest version of ASM.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I've included the [incrementals build](https://ci.jenkins.io/job/Plugins/job/scm-api-plugin/view/change-requests/job/PR-88/) of this plugin in [my test environment](https://github.com/MarkEWaite/docker-lfs/commit/b8c0f74843d5b70268b022e2e0a6919cb8800ace) so that I can see it in operation.  Thanks very much @basil !

**Review by timja — APPROVED** [review]

**Review by jglick — APPROVED** [review]
I guess? But https://github.com/jenkinsci/scm-api-plugin/pull/17#discussion_r91125956

**Comment by basil** [comment]
FYI I dug up [the original post](https://web.archive.org/web/20120701173200/http://weblogs.java.net/blog/kohsuke/archive/2010/02/12/asm-incompatible-changes) where Kohsuke laid out his complaints about ASM. All these complaints seem completely legitimate in the context of ASM 3 in 2010, which definitely seems like it broke compatibility with ASM 2.

As of commit 6a0e7842de436225f3866d3567834c6285107114 in ASM 5.2, ASM added signature tests to avoid breaking backward binary compatibility with any version >= 4.0. These signature tests are still present in `src/test/resources` on the latest version of ASM. So ASM appears to take compatibility seriously these days, starting with ASM 4.

In my opinion, we shouldn't be as nervous about compatibility between ASM 4 and ASM 9 in 2021 as we were about compatibility between ASM 2 and ASM 3 in 2010. Things have changed in the intervening decade.

As long as the original code was compiled against ASM 4 or later, and as long as core ships ASM 4 or later, compatibility should not be a major concern. Both of these are the case with this PR.

**Review by jtnord — APPROVED** [review]

**Comment by timja** [comment]
@car-roll @bitwiseman @dwnusbaum

**Comment by jglick** [comment]
While this seems fine as a quick fix, I would still like to see the ASM dep removed from this plugin, as I believe it is unnecessary—just an overengineered way to get `SCMHead` implementations to define `equals` properly. There are not _that_ many impls

```console
$ find *-plugin/{,*/}src/main/java -type f | xargs fgrep 'extends SCMHead '
bitbucket-branch-source-plugin/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMHead.java:public class PullRequestSCMHead extends SCMHead implements ChangeRequestSCMHead2 {
bitbucket-branch-source-plugin/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BranchSCMHead.java:public class BranchSCMHead extends SCMHead {
bitbucket-branch-source-plugin/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SCMHeadWithOwnerAndRepo.java:public class SCMHeadWithOwnerAndRepo extends SCMHead {
gerrit-code-review-plugin/src/main/java/jenkins/plugins/gerrit/ChangeSCMHead.java:public class ChangeSCMHead extends SCMHead implements ChangeRequestSCMHead2 {
gerrit-plugin/src/main/java/jenkins/plugins/gerrit/ChangeSCMHead.java:public class ChangeSCMHead extends SCMHead implements ChangeRequestSCMHead2 {
gitea-plugin/src/main/java/org/jenkinsci/plugin/gitea/PullRequestSCMHead.java:public class PullRequestSCMHead extends SCMHead implements ChangeRequestSCMHead2 {
gitea-plugin/src/main/java/org/jenkinsci/plugin/gitea/BranchSCMHead.java:public class BranchSCMHead extends SCMHead {
github-branch-source-plugin/src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMHead.java:public class PullRequestSCMHead extends SCMHead implements ChangeRequestSCMHead2 {
github-branch-source-plugin/src/main/java/org/jenkinsci/plugins/github_branch_source/BranchSCMHead.java:public class BranchSCMHead extends SCMHead {
gitlab-branch-source-plugin/src/main/java/org/jenkinsci/plugins/gitlab_branch_source/BranchSCMHead.java:public class BranchSCMHead extends SCMHead {
gitlab-branch-source-plugin/src/main/java/org/jenkinsci/plugins/gitlab_branch_source/MergeRequestSCMHead.java:public final class MergeRequestSCMHead extends SCMHead implements ChangeRequestSCMHead {
git-plugin/src/main/java/jenkins/plugins/git/GitBranchSCMHead.java:public class GitBranchSCMHead extends SCMHead implements GitSCMHeadMixin {
git-plugin/src/main/java/jenkins/plugins/git/GitRefSCMHead.java:public class GitRefSCMHead extends SCMHead implements GitSCMHeadMixin {
git-plugin/src/main/java/jenkins/plugins/git/GitTagSCMHead.java:public class GitTagSCMHead extends SCMHead implements TagSCMHead {
p4-plugin/src/main/java/org/jenkinsci/plugins/p4/scm/P4SCMHead.java:public class P4SCMHead extends SCMHead {
scm-api-plugin/src/main/java/jenkins/scm/api/mixin/ChangeRequestSCMRevision.java:public abstract class ChangeRequestSCMRevision<H extends SCMHead & ChangeRequestSCMHead> extends SCMRevision {
scm-api-plugin/src/main/java/jenkins/scm/api/SCMHead.java:     *     public static class MyChangeRequestSCMHead extends SCMHead implements ChangeRequestSCMHead {
scm-manager-plugin/src/main/java/com/cloudogu/scmmanager/scm/api/ScmManagerHead.java:public class ScmManagerHead extends SCMHead {
tuleap-git-branch-source-plugin/src/main/java/org/jenkinsci/plugins/tuleap_git_branch_source/TuleapBranchSCMHead.java:public class TuleapBranchSCMHead extends SCMHead {
github-integration-plugin/github-pullrequest-plugin/src/main/java/com/github/kostyasha/github/integration/multibranch/head/GitHubSCMHead.java:public abstract class GitHubSCMHead<T extends GitHubCause<T>> extends SCMHead {
github-pullrequest-plugin/github-pullrequest-plugin/src/main/java/com/github/kostyasha/github/integration/multibranch/head/GitHubSCMHead.java:public abstract class GitHubSCMHead<T extends GitHubCause<T>> extends SCMHead {
```

so we could have a default impl using reflection and issuing a runtime warning, then override it in the most widely used plugins for efficiency.

**Review by car-roll — APPROVED** [review]

**Comment by timja** [comment]
Can we get a release please @car-roll @bitwiseman @kshultzCB @dwnusbaum

**Comment by jglick** [comment]
(and consider this plugin for JEP-229)

**Comment by timja** [comment]
Can we get a release please @car-roll @bitwiseman @kshultzCB @dwnusbaum

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
